### ISSUE TITLE
各节点服务器配置咨询

### ISSUE THREAD

**Issue by goofyan** [sofastack/sofa-registry#10]
请分别提供下meta/session/data节点运行的服务器推荐配置：包括OS版本/位数、CPU性能、存储要求、网卡要求、是否可使用虚拟机等。谢谢~

**Comment by atellwu** [comment]
- CPU性能、存储要求： 规模不大可以2核4G，规模较大推荐4核8G，SOFARegistry数据都存储在内存，磁盘主要用于日志的打印，占用不大，在日志可以定期清理的基础上，20G以上即可。
- OS版本/位数/虚拟机：理论上只要支持java8及以上的OS即可，建议64位，虚拟机是可以的，目前蚂蚁金服内部的SOFARegistry也是运行在虚拟机上(64位4C8G)。
- 网卡要求：SOFARegistry的数据传输主要是增量数据，所以对带宽消耗是比较节省的。当然实际的带宽需求受业务规模(服务的注册量)影响，所以建议经过实际测试后再确定，规模比较大建议千兆网卡以上。
