### ISSUE TITLE
!! registry-integration start failed

### ISSUE THREAD

**Issue by YuGanRepo** [sofastack/sofa-registry#105]
### Your question

!! registry-integration start failed，So that the RPC service request fails.

### Your scenes

![image](https://user-images.githubusercontent.com/27922304/79439984-10501980-8008-11ea-9052-7ddb0f5def41.png)

### Environment

- SOFARegistry version: 5.4.0 & 5.4.2
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): Mac Os
- Maven version: 3.6

**Comment by tylorswift** [comment]
I had recieved same question during started the registry-integeration  startup.bat  . 同病相怜

**Comment by khotyn** [comment]
I'll check this problem later.

**Comment by khotyn** [comment]
你是在什么目录下启动 sofa-registry 的？

**Comment by khotyn** [comment]
可以把整个日志目录给放上来。

**Comment by dzdx** [comment]
新版本已经移除rocksdbjni依赖
