### ISSUE TITLE
MetaNodeExchanger 的connectServer应该只是连接其中一台meatserver就好吧

### ISSUE THREAD

**Issue by huangyunbin** [sofastack/sofa-registry#11]
![image](https://user-images.githubusercontent.com/1046037/56402953-fd3e2880-6291-11e9-8269-4a082f2fdcfa.png)
代码中看到是连接这个数据中心所有的meatserver的，这个不太合理吧，连接其中一台就可以了吧

**Comment by atellwu** [comment]
对，确实没必要连所有meta，后续我们会优化这一点。谢谢您的指正~
