### ISSUE TITLE
Can the test server register through the public network?

### ISSUE THREAD

**Issue by AlberZ1989** [sofastack/sofa-registry#125]
想把开发环境的注册中心部署在云端?
有办法吗?

**Comment by AlberZ1989** [comment]
Want to deploy the registration center of the development environment in the cloud? Is there a way?

**Comment by NickNYU** [comment]
@AlberZ1989 我们现在启动了两个计划，重新点亮sofa-registry社区，这个需求有兴趣认领一下吗？

**Comment by NickNYU** [comment]
track this in https://github.com/sofastack/sofa-registry/issues/172

**Comment by Xunzhuo** [comment]
@NickNYU I am interested in this too, after solving #173. I will spend time making this #172 happen. Please assign this to me, if there is no one to work this on.
