### ISSUE TITLE
Any http api fetch pub/sub detail (like IP)

### ISSUE THREAD

**Issue by kentchenjh** [sofastack/sofa-registry#128]
since sofa registry did not have dashboard, and I want to aggregate all pub/sub info together (just like eureka, every app and every instance in app, each instance has its own IP). It seems sofa registry do not provider these kinds of APIs, I only found getDataInfoIdList in session server which maybe helpful. 

So is there any useful APIs to address this situation? Do I need to implement non-Java client to fetch these info, like (golang, python etc)

**Comment by dzdx** [comment]
There is no aggregate interface yet, you can query publisher and Subscriber via the dataInfoId

- list dataInfoId in session node
   `$sessionIP:9603/digest/getDataInfoIdList`

example:
dataInfoId==`com.dzdx.test#@#DEFAULT_INSTANCE_ID#@#DEFAULT_GROUP`
urlencode($dataInfoId) ==`com.dzdx.test%23%40%23DEFAULT_INSTANCE_ID%23%40%23DEFAULT_GROUP`

- query publishers by dataInfoId in session node 
   `$sessionIP:9603/digest/pub/data/query?dataInfoId=com.dzdx.test%23%40%23DEFAULT_INSTANCE_ID%23%40%23DEFAULT_GROUP` 
- query subscribers by dataInfoId in session node
   `$sessionIP:9603/digest/sub/data/query?dataInfoId=com.dzdx.test%23%40%23DEFAULT_INSTANCE_ID%23%40%23DEFAULT_GROUP` 

- query publishers by dataInfoId in data node
    `$dataIP:9622/digest/datum/query?dataId=com.dzdx.test&group=DEFAULT_GROUP&instanceId=DEFAULT_INSTANCE_ID` 


https://github.com/sofastack/sofa-registry/blob/9bcab36653c7ef70d09d66e5a9e3bf89723a929b/server/server/session/src/main/java/com/alipay/sofa/registry/server/session/resource/SessionDigestResource.java#L104

**Comment by kentchenjh** [comment]
thanks for your reply, the apis in session server work for me.

**Comment by kentchenjh** [comment]
It seems publishers from session node contain confused port number, for example a publisher opens a dubbo protocol port as 20880, the publisher info from session would contain a fixed "random" port instead of 20880 which seems like useless. After I read source code in dubbo implement(https://github.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-sofa/src/main/java/org/apache/dubbo/registry/sofa/SofaRegistry.java#L126). It put real port and other valuable info in extra data, and it will be serialized, but the serialized string returned by session is pointless which is not human readable. Is there any plan to solve this?
