### ISSUE TITLE
我想单独使用注册中心，可能的服务有java和python，支持python服务接口的注册吗

### ISSUE THREAD

**Issue by 122093404** [sofastack/sofa-registry#130]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARegistry version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by bjxiaojian** [comment]
registry注册中心是支持各个语言的服务发现和订阅的，目前开源版中只有java client。需要实现其他语言的服务发现和订阅，需要自己实现相关语言的registry client。

**Comment by 122093404** [comment]
> RegistryRegistrationCenter是支持各种语言的服务发现和订阅的，目前开放版本中只有Java客户。实现其他语言的服务发现和订阅，需要自己实现相关语言的注册客户。



> RegistryRegistrationCenter是支持各种语言的服务发现和订阅的，目前开放版本中只有Java客户。实现其他语言的服务发现和订阅，需要自己实现相关语言的注册客户。

sofa-bolt-python的服务发现与服务发布，不能注册到注册中心吗，这个仅是RPC调用吗

**Comment by NickNYU** [comment]
@122093404 目前我们启动了deep-dive计划，欢迎认领这个任务

**Comment by NickNYU** [comment]
will track this issue on project issue: https://github.com/sofastack/sofa-registry/issues/167
