### ISSUE TITLE
配置的registryEndpoint如果不可以用，是否会影响到session serverList的同步

### ISSUE THREAD

**Issue by dayuange123** [sofastack/sofa-registry#142]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARegistry version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dzdx** [comment]
会影响的， client是通过 registryEndpoint用http请求的方式获取到session serverList
