### ISSUE TITLE
服务数据是否无法保证多副本？

### ISSUE THREAD

**Issue by goofyan** [sofastack/sofa-registry#18]
基础环境：3meta+3data+2session。各个data节点配置storeNodes=3。data节点ip：7，8，9
现增加一个data节点做扩容，storeNodes也配置为3。ip为53
服务注册时主副本写到53节点，53节点计算后给7和9发送NotifyDataSyncRequest，但是9在处理完该datum后，又执行LocalDataServerCleanHandle，clean了该服务数据
导致该服务只在53和7中存了两个副本
----引申之，是否存在以下可能性：主副本给其他2个data节点同步数据，但是这2个节点都将该数据clean了，导致服务数据只存在主副本这一个副本？
----是否集群中data节点越多，以上风险就越大？
----另外，验证若配置主副本data节点的storeNodes为1时，将主副本的data节点停机后，在其他data节点上查不到注册的服务数据。所以如果数据不能保证多副本，存在注册数据丢失的风险？

请确认是否为bug。

谢谢！

**Comment by Synex-wh** [comment]
首先感谢你对我们系统多节点复制功能的详细了解和测试，以及对代码的深入了解
其次，对于你所描述的场景，我可能理解有些偏差，是否可以给一个即时沟通的方式我们详细聊一下你的验证场景。
按照你描述我所理解的扩容场景，新的节点（ip 53）必须同步完其他节点的数据，变为working状态才可以开始接受新增数据写入（之前禁写读转发），并且对于新写入的数据进行多副本复制，这个过程其他现有节点（假设你要同步到的是7和9）应该已经获取到了最新列表（包含53的全量列表），LocalDataServerCleanHandle任务是会根据最新列表计算不属于当前节点的数据进行清理，为啥会清理掉你所说53同步过来的数据，我不是很理解，我们是否可以交流，我们也可以按照你描述尝尽进行进一步验证，也不排除我们验证的场景缺失

**Comment by goofyan** [comment]
这边有没有开发者沟通群之类的？不然我不知道怎么给您隐蔽点的即时沟通方式哈
我的场景是，新节点加入前集群中有几个服务目录，但是都没有提供方和订阅方。后来加入新节点，过了很久后才启动一个提供方（主副本在新节点）。我理解应该不存在启动提供方前各个节点数据不同步的问题
另外，我看LocalDataServerCleanHandle的run代码，clean的条件是!backupTriad.containsSelf()，backupTriad的ipSetOfNode又是由ConsistentHash.getNUniqueNodesFor计算来的。按我理解，ipSetOfNode的大小不会超过storeNodes的大小，即3，而在实际data节点超过3时必然会有缺失-----当然我也可能理解错了这两个方法的含义了~望指点~

**Comment by ujjboy** [comment]
@goofyan  钉钉群 23127468

**Comment by goofyan** [comment]
钉钉群加了帮忙给通过下~
另外补充个场景：还是以上环境-主副本data节点53，另外一个副本data节点7
现在停53的进程，用http://ip:9622/digest/datum/query查询，该服务只在节点7能查询出提供方信息，于是认为节点7并未再将服务备份给其他data节点。而我此时再把节点7的进程停掉，新起一个订阅方服务不能调用了，报错提供方不存在。
请确认~谢谢！
另说明，我是用你们提给dubbo归并的SofaRegistry类基于dubbo进行服务调用验证的

**Comment by Synex-wh** [comment]
我在钉钉群里联系过你是否在群里描述一下问题 @goofyan
