### ISSUE TITLE
官网文档长期未更新

### ISSUE THREAD

**Issue by yang724687930** [sofastack/sofa-registry#194]
SofaRegisty的官网文档显示更新时间还是2019年，何时更新最新文档

**Comment by dzdx** [comment]
最近更新的新版本主要在服务端上，所以官方文档只更新了服务端部署的文档：  
https://www.sofastack.tech/projects/sofa-registry/server-quick-start/    
对外的接口和客户端没有变化，后续会继续更新api文档和blog，欢迎关注
