### ISSUE TITLE
源码解析: SlotTable

### ISSUE THREAD

**Issue by dzdx** [sofastack/sofa-registry#197]
### 介绍

SOFARegistry对于服务数据是分片进行存储的，因此每一个data server只会承担一部分的服务数据，具体哪份数据存储在哪个data server是有一个称为SlotTable的路由表提供的，session可以通过SlotTable对对应的data derver进行读写服务数据， slot对应的data follower可以通过SlotTable寻址leader进行数据同步。
维护SlotTable是由meta的leader负责的，meta会维护data 的列表，会利用这份列表以及data上报的监控数据创建SlotTable，后续data的上下线会触发meta修改SlotTable， SlotTable会通过心跳分发给集群中各个节点。

### 架构流程图
![image](https://user-images.githubusercontent.com/7933207/157151757-49fdc5d6-502e-4706-9cd3-ec79e685a8a9.png)

### 参考解析
- SlotTable的结构以及session和data如何使用SlotTable
- SlotTable的生成和变更算法
- 分发变更到其他节点的过程

###  参考阅读
```
com.alipay.sofa.registry.server.meta.slot.arrange.ScheduledSlotArranger#arrangeSync
com.alipay.sofa.registry.server.meta.slot.*
com.alipay.sofa.registry.server.meta.remoting.handler.HeartbeatRequestHandler
com.alipay.sofa.registry.server.data.remoting.metaserver.MetaServerServiceImpl#handleRenewResult
com.alipay.sofa.registry.server.session.node.service.MetaServerServiceImpl#handleRenewResult
...
```

**Comment by paojiao-fengzhua** [comment]
> /assign

欢迎，可以加下"SOFARegistry开发者团队"的群，过程中遇到问题方便沟通
钉钉群号35524433

**Comment by xingdong015** [comment]
[SofaRegistry中 SlotTable详解.md](https://github.com/sofastack/sofa-registry/files/8447788/SofaRegistry.SlotTable.md)
