### ISSUE TITLE
源码解析：无损运维

### ISSUE THREAD

**Issue by dzdx** [sofastack/sofa-registry#198]
### 介绍

SOFARegistry是一个基于内存存储的分布式注册中心，数据是分散存储在各个节点，为了做到注册中心自身运维期间依然能够对外正常提供服务，需要进行节点下线快速感知和数据迁移。

- session存储client发送的发布和订阅数据，由于client断连重放的特性，session单机下线后client会重放数据到其他节点
- data会接收session发送的发布数据，data单机下线后，meta会通过SlotTable的变更把对应Slot的所有权移交其他data，data启动后会进行数据同步到达数据完整可对外提供服务的状态

### 架构流程图
![image](https://user-images.githubusercontent.com/7933207/157151953-562ec903-409c-4eb0-bc78-d42fca0df664.png)

### 参考解析
- session、data下线的过程，如何避免下线期间数据丢失和抖动
- meta 如何处理 session、data 主动下线的请求通知
- data 启动期如何
- client重连回放机制
- 解析data的启动过程的状态转化，如何确保新分配的slot的数据完整性

###  参考阅读
```
com.alipay.sofa.registry.server.session.bootstrap.SessionServerBootstrap#doStop
com.alipay.sofa.registry.server.data.bootstrap.DataServerBootstrap#doStop
com.alipay.sofa.registry.server.meta.remoting.handler.RegistryForbiddenServerHandler
com.alipay.sofa.registry.server.meta.lease.session.DefaultSessionServerManager#getSessionServerMetaInfo
com.alipay.sofa.registry.server.meta.lease.data.DefaultDataServerManager#getDataServerMetaInfo
com.alipay.sofa.registry.server.data.slot.SlotManagerImpl#syncMigrating
com.alipay.sofa.registry.client.remoting.ClientConnection#ensureConnected
```

**Comment by zswaaa** [comment]
assign it to me

**Comment by zswaaa** [comment]
Sorry,i clicked wrong button,still in analyzing.

**Comment by zswaaa** [comment]
[源码解析：无损运维.md](https://github.com/sofastack/sofa-registry/files/8460114/default.md)

**Comment by zswaaa** [comment]
[无损运维.md](https://github.com/sofastack/sofa-registry/files/8460360/default.md)

**Comment by zswaaa** [comment]
[源码解析：无损运维.md](https://github.com/sofastack/sofa-registry/files/8468359/default.md)

**Comment by zswaaa** [comment]
[无损运维.md](https://github.com/sofastack/sofa-registry/files/8468764/default.md)
