### ISSUE TITLE
源码解析：推送延迟trace

### ISSUE THREAD

**Issue by dzdx** [sofastack/sofa-registry#199]
### 介绍

对于分布式注册中心，整个推送过程涉及到很多的流程和节点，如何计算从发布端变更到广播给全集群所有的订阅方的延迟，每个阶段的延迟分别是多少对排查集群内部的问题及注册中心的负载具有比较大的价值，因此需要对整个推送过程进行延迟链路跟踪

### 参考解析
- 推送延迟的计算方式
- 首次订阅和后续推送延迟计算的区分
- 如何统计各个阶段的耗时

###  参考阅读
```
com.alipay.sofa.registry.common.model.TraceTimes
com.alipay.sofa.registry.server.session.push.PushTrace
com.alipay.sofa.registry.server.session.push.PushProcessor.PushClientCallback#onCallback
```

**Comment by dzdx** [comment]
@kuaile-zc  欢迎，可以加下"SOFARegistry开发者团队"的群，过程中遇到问题方便沟通
钉钉群号35524433

**Comment by kuaile-zc** [comment]
https://note.youdao.com/s/KRcsedNx

**Comment by kuaile-zc** [comment]
[sofa-regsitry延迟推送trace源码解析.md](https://github.com/sofastack/sofa-registry/files/8330823/sofa-regsitry.trace.md)
