### ISSUE TITLE
源码解析：通讯数据压缩

### ISSUE THREAD

**Issue by dzdx** [sofastack/sofa-registry#200]
### 介绍

为了支撑超大规模集群，SOFARegistry的data和session以及session和client (目前只有go支持）都添加了对压缩数据传输的支持，同时为了减少压缩cpu的消耗，对于压缩后数据添加了缓存

### 参考解析
- 通讯两端对于压缩算法的协商机制
- 哪些地方的数据传输使用了压缩，哪些地方使用了压缩缓存

###  参考阅读
```
com.alipay.sofa.registry.compress.*
com.alipay.sofa.registry.server.data.remoting.sessionserver.handler.GetDataHandler
com.alipay.sofa.registry.server.session.push.PushDataGenerator#createPushData
```

**Comment by tkz2020** [comment]
assign

**Comment by dzdx** [comment]
@tkz2020  欢迎，可以加下"SOFARegistry开发者团队"的群，过程中遇到问题方便沟通
钉钉群号35524433

**Comment by paojiao-fengzhua** [comment]
> /assign

欢迎，可以加下"SOFARegistry开发者团队"的群，过程中遇到问题方便沟通
钉钉群号35524433

**Comment by czbcxy** [comment]
[SOFARegistry通讯数据压缩.md](https://github.com/sofastack/sofa-registry/files/8378179/SOFARegistry.md)
