### ISSUE TITLE
源码解析：推送开关

### ISSUE THREAD

**Issue by dzdx** [sofastack/sofa-registry#201]
### 介绍

某些场景下SOFARegistry需要暂时关闭推送功能，这样集群内的业务可以利用client的缓存继续工作，比如说SOFARegistry需要进行不兼容升级，需要全集群下线，更新版本后再拉起。
推送开关的状态存储在数据库中，通过meta修改数据后，session可以通过读取到推送开关的变更通知，并在对应的推送流程上进行切断

### 参考解析
- meta如何存储开关配置数据
- session如何获取到开关配置的变更并触发更新（通知、定时）
- session关闭推送功能的实现

###  参考阅读
```
com.alipay.sofa.registry.server.meta.resource.StopPushDataResource#closePush
com.alipay.sofa.registry.server.meta.provide.data.DefaultProvideDataService
com.alipay.sofa.registry.server.session.remoting.handler.NotifyProvideDataChangeHandler
com.alipay.sofa.registry.server.shared.providedata.SystemPropertyProcessorManager
com.alipay.sofa.registry.server.shared.providedata.BaseStopPushService
com.alipay.sofa.registry.server.session.push.PushSwitchService
```

**Comment by seeflood** [comment]
@hecz12 欢迎，可以加下"SOFARegistry开发者团队"的群，过程中遇到问题方便沟通
钉钉群号35524433

**Comment by YechenGu** [comment]
/assign
Hi, i want to try this issue, is it still available?

**Comment by paojiao-fengzhua** [comment]
> /assign Hi, i want to try this issue, is it still available?

有的，欢迎欢迎～可以加下"SOFARegistry开发者团队"的群，过程中遇到问题方便沟通
钉钉群号35524433

**Comment by YechenGu** [comment]
[推送开关.md](https://github.com/sofastack/sofa-registry/files/8539492/default.md)
