### ISSUE TITLE
源码解析：数据倒排索引

### ISSUE THREAD

**Issue by dzdx** [sofastack/sofa-registry#202]
### 介绍

SOFARegistry有一些场景需要根据 ip:port 反查改连接所对应的所有数据，比如断链清理数据，因此需要一个倒排索引建立 ip:port -> publisher、subscriber 的关系，在超大数据量以及大量断链的场景下不会因为变量而cpu耗尽

### 参考解析
- 倒排索引如何更新，如何维护和对应数据之间的一致性
- 通过索引查询数据的流程

###  参考阅读
```
com.alipay.sofa.registry.server.session.store.AbstractDataManager.ConnectDataIndexer
com.alipay.sofa.registry.server.session.store.DataIndexer
com.alipay.sofa.registry.server.session.store.AbstractDataManager
...
```

**Comment by seeflood** [comment]
@xingdong015 欢迎，可以加下"SOFARegistry开发者团队"的群，过程中遇到问题方便沟通
钉钉群号35524433

**Comment by xingdong015** [comment]
[服务注册中心Session倒排正排索引.md](https://github.com/sofastack/sofa-registry/files/8258964/Session.md)

**Comment by xingdong015** [comment]
[服务注册中心Session倒排正排索引 (1).md](https://github.com/sofastack/sofa-registry/files/8260201/Session.1.md)

**Comment by HKui97** [comment]
这个md文件图片加载不出来？别的md里面图片好像能加载出来，是我电脑问题么？

**Comment by dzdx** [comment]
@HKui97   可以看下这个
https://www.sofastack.tech/projects/sofa-registry/code-analyze/code-analyze-data-inverted-index/
