### ISSUE TITLE
建议增加一个 docker 方式的快速开始

### ISSUE THREAD

**Issue by stulzq** [sofastack/sofa-registry#206]
## In what area(s)?

> /area docs

## Describe the feature

可以弄一个 docker-compose 脚本，让用户可以快速的把 sofa-registry 快速运行起来。

**Comment by seeflood** [comment]
agreed

**Comment by dzdx** [comment]
https://www.sofastack.tech/projects/sofa-registry/deployment/   这边有一个docker 部署的文档，目前还没有提供docker-compose 的方式，考虑主要是快速启动可以用IDE源码直接启动或者直接用 jar 启动。

也欢迎贡献一下docker-compose的启动方式 @stulzq
