### ISSUE TITLE
Informer 导致fgc

### ISSUE THREAD

**Issue by dzdx** [sofastack/sofa-registry#225]
### Describe the bug

Informer上的container由于采用半小时重建一次替换的方式进行更新，所以旧的对象会进入old区，导致old区一直升高引起fgc
![image](https://user-images.githubusercontent.com/7933207/170640150-7d56d4a6-86fe-47bc-94dd-ff15e0912d11.png)

![image](https://user-images.githubusercontent.com/7933207/170640205-8223cc0f-8ffa-467e-b3e3-a5d3347360c4.png)

需要对这部分内存占用进行优化
- InterfaceAppsIndexContainer内的String使用wordcache
- 由于不存在并发写，使用hashmap代替concurrentHashMap

### Environment

- SOFARegistry version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by NickNYU** [comment]
可以尝试依赖off heap的：https://github.com/cfelde/BinaryOffheapHashMap#:~:text=The%20BOHMap%20is%20a%20hashmap,entries%20stored%20in%20the%20map.

也可以自己实现：
https://blogs.oracle.com/javamagazine/post/creating-a-java-off-heap-in-memory-database
