### ISSUE TITLE
当前master代码打包出来的服务端启动健康检查报错

### ISSUE THREAD

**Issue by zhaojigang** [sofastack/sofa-registry#25]
### Your question

hi, 按照 https://www.sofastack.tech/sofa-registry/docs/Server-QuickStart 中自己下载源码包打包的方式，最后启动 server，健康检查报错如下：
![image](https://user-images.githubusercontent.com/14085645/58167718-2998fa80-7cbf-11e9-8a0c-d9921fe60b12.png)
还有这个监控检查是改了吗？lsof -i:9603 发现没进程占用
![image](https://user-images.githubusercontent.com/14085645/58167827-6a910f00-7cbf-11e9-81ef-f2889087ae96.png)

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARegistry version: 5.2.1-SNAPSHOT
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): linux or mac
- Maven version: 3.x
- IDE version: idea

**Comment by Synex-wh** [comment]
你是否使用初始化nodes.metaNode参数使用了127.0.0.1，之前遇到过类似用户，如果不行你可以直接到钉钉群里问我 群号 : 23127468
![image](https://user-images.githubusercontent.com/8018119/58246965-12274380-7d8b-11e9-8f99-7aa5f2ed54f9.png)

**Comment by zhaojigang** [comment]
嗯，默认是localhost，改成 127.0.0.1 也不行

**Comment by Synex-wh** [comment]
你的mac还是win？换成当前ifconfig里的ip也不行么？我看你这个图截得是session的，是否其他角色ok呢，比如meta的curl http://{meta ip}:9615/health/check，按照你的图说的9603端口没有启动监听，应该在错误日志里爆错了，请贴一下具体原因，不行钉钉详细聊

**Comment by zhaojigang** [comment]
感谢 @Synex-wh ，这个是因为我使用 jdk10 打了包，所以会出问题，改为 jdk8 去打包就 ok 了
