### ISSUE TITLE
meta节点咨询

### ISSUE THREAD

**Issue by goofyan** [sofastack/sofa-registry#26]
meta节点如果发生一台或多台宕机，会有哪些影响？
比如，是否影响服务注册、订阅；是否影响data或session节点上下线；是否影响服务数据备份？

----------------------------------------------

我们测试集群配置3meta3data2session，5.2.0开源版本，启动服务提供方后，停掉一个meta节点，启动订阅方，报找不到提供方。
这结论是否正确？meta节点是否会成为瓶颈？

**Comment by Synex-wh** [comment]
meta 节点之间通过raft协议保证一致性，多个节点节点注册ip数据一致。半数以上节点宕机无法选举无法保证高可用，比如3台机器1台宕机仍然保证数据一致高可用，但是如果2台宕机剩余一台，数据无法保证其他节点复制，剩余一台只能保证基本功能无法保证数据一致，所有meta宕机其他session和data节点变化无法感知，单不影响影响服务注册、订阅。

5.2.0版本存在一个meta宕机会影响整个集群的一个bug，详见 #24，已经修正后续5.2.1发布

**Comment by goofyan** [comment]
5.2.1预计什么时候发布？

**Comment by dzdx** [comment]
已发布
