### ISSUE TITLE
feature: custom client IP

### ISSUE THREAD

**Issue by dzdx** [sofastack/sofa-registry#265]
# 场景
在某些情况下，client和session并不是直连，比如跨VPC，需要通过lb进行连接，此时由于注册中心看到的remoteAddress并不是PodIP，会导致按IP关流，黑名单能功能失效，注册中心需要支持读取client上传的自定义IP，作为关流和黑名单的查找key
![image](https://user-images.githubusercontent.com/7933207/186649831-196710c2-1525-4c43-9dbb-8f761262fbf8.png)
比如在这边的场景中
希望对ip1加黑，但注册中心看到的请求对应链接的地址都是ip3, 而对ip3加黑会把全部app的pub/sub全部加黑。

- client 支持setIP
- registry 看到如果pub.ip和connection.remoteAddress不一样，需要采用pub.ip作为索引

**Comment by it-linnan** [comment]
我这边也遇到了这个问题，应用部署在k8s上，注册中心获取到的是node ip，如果直接用node ip加黑，会导致这个node上的所有pod都下线。。
有什么改造思路吗？

**Comment by NickNYU** [comment]
> 我这边也遇到了这个问题，应用部署在k8s上，注册中心获取到的是node ip，如果直接用node ip加黑，会导致这个node上的所有pod都下线。。 有什么改造思路吗？

这个问题的本质还是服务治理的一个颗粒度的问题：也就是说，目前的SOFARegistry的服务治理是以IP为维度的。

这个问题有两种解法：
1. 细化SOFARegistry的服务治理的颗粒度。这个就是V5到V6平滑升级设计的核心思路，将原有的consistent-hash以一个data node的颗粒度，拆分为一个逻辑slot的颗粒度进行数据的迁移。
2. 推荐你引入专门服务治理的组件。我举个不恰当的例子，如果你也引入了istio，就可以通过多维度的filter去禁掉某个endpoint。

服务治理这块儿，目前看Nacos好像也没有做到很完美，Nacos体系的更多能力还是靠Sentinel这种进行辅助。所以，如果紧急的话，可以考虑看看自己是否有现成的服务治理组件

**Comment by it-linnan** [comment]
> > 我这边也遇到了这个问题，应用部署在k8s上，注册中心获取到的是node ip，如果直接用node ip加黑，会导致这个node上的所有pod都下线。。 有什么改造思路吗？
> 
> 这个问题的本质还是服务治理的一个颗粒度的问题：也就是说，目前的SOFARegistry的服务治理是以IP为维度的。
> 
> 这个问题有两种解法：
> 
> 1. 细化SOFARegistry的服务治理的颗粒度。这个就是V5到V6平滑升级设计的核心思路，将原有的consistent-hash以一个data node的颗粒度，拆分为一个逻辑slot的颗粒度进行数据的迁移。
> 2. 推荐你引入专门服务治理的组件。我举个不恰当的例子，如果你也引入了istio，就可以通过多维度的filter去禁掉某个endpoint。
> 
> 服务治理这块儿，目前看Nacos好像也没有做到很完美，Nacos体系的更多能力还是靠Sentinel这种进行辅助。所以，如果紧急的话，可以考虑看看自己是否有现成的服务治理组件

好的，我这边考虑下引入服务治理组件。🙏
