### ISSUE TITLE
DataNodeServiceImpl内部实现不内聚（BlockingQueues和对应Worker操作）

### ISSUE THREAD

**Issue by dbl-x** [sofastack/sofa-registry#284]
### Your question

DataNodeServiceImpl内部拥有线程池执行写入操作，每个线程对应是的一个Worker（Runnable实现），Worker实现从绑定的一个Queue中打包数据进行发送。

数据写入流程：
* 外部数据写入->DataNodeServiceImpl#commitReq()->BlockingQueues#put()->Queue#offer()
数据读取流程：
* Worker->Queue#poll
可见数据的写入和读取流程分别操作的对象是BlockingQueues和内部的Queue，并没有一个统一的抽象将Worker和Queue组合到一起，或者统一读写接口到BlockingQueues上，做到代码的内聚。

### Your scenes

仅阅读代码，无具体场景。

### Your advice

将缓存和对应的线程池进行组合，抽象成一个对象，做到将数据的写入、攒批、发送内聚到一个对象中。

### Environment

- SOFARegistry version: 6.1.9
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by NickNYU** [comment]
我这几天在想，这块儿是不是我们可以用LMAX优化下？
目前注册中心大量地使用了队列去做聚合、批处理以及异步解耦。
LMAX在这方面有很好的优化措施，例如，它的一些关键参数通过增加PADDING来解决CPU False Sharing的问题；无锁队列解决了锁的损耗；自带批处理能力等等

是不是顺着这波重构，直接优化下

**Comment by bjxiaojian** [comment]
注册中心大量地使用了队列去做聚合、批处理
---
这个处理主要是两个目的

> 我这几天在想，这块儿是不是我们可以用LMAX优化下？ 目前注册中心大量地使用了队列去做聚合、批处理以及异步解耦。 LMAX在这方面有很好的优化措施，例如，它的一些关键参数通过增加PADDING来解决CPU False Sharing的问题；无锁队列解决了锁的损耗；自带批处理能力等等
> 
> 是不是顺着这波重构，直接优化下

注册中心大量地使用了队列去做聚合、批处理
---
这个处理主要是两个目的，一个是通过攒批降低注册中心自身的一些负载，另一个是降低一些推送频率，降低对订阅端的负载；
目前注册中心也正在做推送时效的提升，中长期方案上可以一起调研和关注一下LMAX @huanglongchao
