### ISSUE TITLE
IO压力及日志文件咨询

### ISSUE THREAD

**Issue by goofyan** [sofastack/sofa-registry#32]
测试环境3meta 3data 2session，5.2.0开源版本
200个tps注册200w提供方，data节点iops高达12000。这是否是写日志文件导致的？
日志目录下该天cache-digest.log为700多M，这是否是必须记的？有什么作用？
另外，请问，按生产运维经验，其他日志文件有哪些是必须记的，有哪些是可以提高日志级别不记或少记的？

**Comment by Synex-wh** [comment]
dataServer这里的日志之前版本确实规划的不好，这个我们后续版本还在进行拆分。cache-digest.log这个实际上是定时把所有内存数据进行摘要dump，这个量确实比较大，但是会反映那一时刻内存数据的情况。后面我们考虑进行简化这个输出，体现在流水数据输出这个就不定期执行

**Comment by atellwu** [comment]
PS: 如有需要，您可以修改cache-digest.log的打印频率（默认是30s打印一次内存数据）。具体见这个类：com.alipay.sofa.registry.server.data.cache.CacheDigestTask

**Comment by dzdx** [comment]
cache-digest.log 已添加开关可以关闭
