### ISSUE TITLE
SOFARegistry的分片策略可以优化一下

### ISSUE THREAD

**Issue by NickNYU** [sofastack/sofa-registry#321]
## In what area(s)?
MetaServer 分片逻辑优化

## Describe the feature

参考Polar-DB这篇文档，分片逻辑决定了挂掉机器后，数据的可用性
[分布式数据库，挂掉两台机器会发生什么](https://zhuanlan.zhihu.com/p/628310849)

### 当前模型
![https://pic1.zhimg.com/80/v2-202d504d2ea29bfcc98bb4ae19c42b8c_720w.webp](https://pic1.zhimg.com/80/v2-202d504d2ea29bfcc98bb4ae19c42b8c_720w.webp)

我们均匀的将12个leader副本分散在集群中，每个节点分配到两个leader副本，除了这两个限定条件，分片与分片之间的调度是无关系的。

目前市面上常见的使用分布式KV+SQL的分布式数据库，一般使用的都是此类模型。

这种情况下，如果挂两台机器，我们分析下会是什么样的情况。 例如，节点1和节点2同时宕机，由于p1、p6均有两个副本在这两个节点上，因此p1和p6处于不可用的状态。 我们枚举一下可能出现的情况：

宕机的节点 | 不可用的分片 | 不可用的分片数
-- | -- | --
1 2 | 1 6 | 2
1 3 | 1 6 | 2
1 4 | 2 8 | 2
1 5 | 2 11 | 2
1 6 | 8 3 11 | 3
2 3 | 6 4 1 9 | 4
2 4 | 4 12 | 2
2 5 | 9 | 1
2 6 | 3 12 | 2
3 4 | 4 7 | 2
3 5 | 5 7 9 | 3
3 6 | 5 | 1
4 5 | 7 10 2 | 3
4 6 | 8 10 12 | 3
5 6 | 5 10 11 | 3

一个比较直观的事实：在此模型下，任意挂两台机器，均会导致部分数据不可用。

设分片数不是12而是M，机器数不是6而是N，我们做几个简单的计算：
![https://pic2.zhimg.com/80/v2-4d5cd594d160a733487606a6d2c3a6c5_720w.webp](https://pic2.zhimg.com/80/v2-4d5cd594d160a733487606a6d2c3a6c5_720w.webp)

以一个N=50节点的集群为例，我们看一下m的取值与可用性的概率关系：
![https://pic3.zhimg.com/80/v2-8bff09149f479d9aa0e5d0c05433e016_720w.webp](https://pic3.zhimg.com/80/v2-8bff09149f479d9aa0e5d0c05433e016_720w.webp)

### 模型2，分片之间存在一定的绑定关系的调度
在模型1中，m的值上升后，由于指数关系，可用性会迅速下降。如果M仅与节点数N相关，而与单节点副本数m无关，则能将可用性维持在一个比较好的数字上。
![https://pic4.zhimg.com/80/v2-abe2c46abd3d3b66ea1f5f37f71280d7_720w.webp](https://pic4.zhimg.com/80/v2-abe2c46abd3d3b66ea1f5f37f71280d7_720w.webp)

在模型2中，我们将节点每三个组成一个组，每个组的每个节点，所包含的副本来自相同的分片，如上图所示。p1-p6、p7-p12各属于一个组。我们枚举一下可能出现的情况：

宕机的节点 | 不可用的分片 | 不可用的分片
-- | -- | --
1 2 | 1 2 3 4 5 6 | 6
1 3 | 1 2 3 4 5 6 | 6
1 4 | 无 | 0
1 5 |   | 0
1 6 |   | 0
2 3 | 1 2 3 4 5 6 | 6
2 4 |   | 0
2 5 |   | 0
2 6 |   | 0
3 4 |   | 0
3 5 |   | 0
3 6 |   | 0
4 5 | 7 8 9 10 11 12 | 6
4 6 | 7 8 9 10 11 12 | 6
5 6 | 7 8 9 10 11 12 | 6

计算下，任意挂两台机器，完全可用或者不丢数据（不存在不可用或者丢数据的分片）的概率为：

![https://pic3.zhimg.com/80/v2-057e4e2b05be7602f5b2b5237a4f0bce_720w.webp](https://pic3.zhimg.com/80/v2-057e4e2b05be7602f5b2b5237a4f0bce_720w.webp)

**Comment by bjxiaojian** [comment]
1. 我理解issue主要还是在db这种数据强一致的场景下，讨论3副本符合调度，以及挂掉两个副本之后的可用性影响分析。
2. registry data上现在确实有类似的调度策略，基本上可以看成是里面模式1的随机调度。问题之所以没有db的影响大，是因为registry挂掉两个副本之后，数据是可以从session恢复，不会完全变成不可用。所以对文章中说到的业务影响才没有这么深的体会。
3. 模式2这种调度模式下面，看起来节点是需要进行编号，这样似乎节点的状态性会比现在的状态更强一些？而且也需要考虑节点在正常运维情况下的一些问题。

**Comment by NickNYU** [comment]
目前的模式下，确实不用动，留作以后data用类似etcd的东西替代后，再考虑这个问题。

这个ISSUE我先close掉了，后面用的话，搜索过来就行。
