### ISSUE TITLE
registry-test is not uploaded to maven central repository since 6.0.0

### ISSUE THREAD

**Issue by khotyn** [sofastack/sofa-registry#327]
SOFARPC depends on `com.alipay.sofa:registry-test` for test. But registry-test has not uploaded to the maven central repo since 6.0.0, the latest one is 

<img width="1004" alt="image" src="https://github.com/sofastack/sofa-registry/assets/584455/caa7950f-bb96-47de-acad-e3e20bd3f84e">

Pls upload registry-test to the maven central repo, tks.

**Comment by huanglongchao** [comment]
Uploading the intermediate version needs to resolve the maven javadoc rules specification.
In the latest version, we fix the maven javadoc rules specification and uploaded
![image](https://github.com/sofastack/sofa-registry/assets/20107380/951735d6-14a0-4e55-b390-02003f08e5e6)
