### ISSUE TITLE
本文件注册中心

### ISSUE THREAD

**Issue by opjkjava** [sofastack/sofa-registry#33]
### Your question
说明文档中有一段话，“本地文件注册中心一般用于测试” ，
是本地文件注册中心有性能问题么？

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARegistry version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by atellwu** [comment]
您好，是在哪份文档里看到的？ 麻烦链接贴出来一下？
