### ISSUE TITLE
千万pub+sub部署咨询

### ISSUE THREAD

**Issue by goofyan** [sofastack/sofa-registry#34]
咨询下，如果生产上需支持千万级别的pub+sub，以各500w为例，meta/session/data节点建议如何部署：是否需要部署多个区域？各个节点分别需要几台？服务器配置推荐什么规格？

**Comment by dzdx** [comment]
建议4c8g部署， data按照单机100w pub ， 双副本考虑单机50w，   session = data * 4  500w容量预计是10 data, 40 session
