### ISSUE TITLE
Issue of high CPU usage by the meta leader

### ISSUE THREAD

**Issue by huanglongchao** [sofastack/sofa-registry#340]
cause by Poor performance fasterxml jackson & No cleanup mechanism on operator.node blacklist

![image](https://github.com/sofastack/sofa-registry/assets/20107380/1ffe8e2f-292f-409f-ab6f-b8bf600bb448)

after clean up
 
![image](https://github.com/sofastack/sofa-registry/assets/20107380/7313a1c9-de58-45f0-b3a4-fbe8f029a716)

**Comment by nocvalight** [comment]
i think we can maintain a version and operator object in memory, skip deserialize when version in memory equals to version in db.

**Comment by NickNYU** [comment]
sounds kind of like a distributed configuration center
Comparing with `Nacos`, `config center` is also a considerable functionality for `SOFARegistry`

**Comment by huanglongchao** [comment]
Absolutely right.

Moreover， When dealing with more than 100+ data points, the benchmark results indicate that Gson outperforms Jackson by a factor of 5 in terms of performance.  replace Jackson with Gson when deserialize  operator.node blacklist

**Comment by huanglongchao** [comment]
sounds like a major project.

**Comment by huanglongchao** [comment]
sounds like a major project.
