### ISSUE TITLE
引用了错误的jetty版本10.0.0-alpha0

### ISSUE THREAD

**Issue by jimchou800** [sofastack/sofa-registry#39]
### Describe the bug
clone源码后，执行 
```
mvn clean package -DskipTests 
```
### Expected behavior
 编译成功

### Actual behavior
报错:
```
/E:/sofastack/sofa-registry/server/remoting/http/src/main/java/com/alipay/sofa/registry/remoting/jersey/jetty/server/HttpChannelOverHttpCustom.java:[19,30] 无法访问org.eclipse.jetty.http.HttpVersion
[ERROR]   错误的类文件: D:\tool\apache-maven-3.5.3\repo\org\eclipse\jetty\jetty-http\10.0.0-alpha0\jetty-http-10.0.0-alpha0.jar(org/eclipse/jetty/http/HttpVersion.class)
[ERROR]     类文件具有错误的版本 55.0, 应为 52.0
```
### Minimal yet complete reproducer code (or GitHub URL to code)
```
sofa-registry/server/remoting/http/src/main/java/com/alipay/sofa/registry/remoting/jersey/jetty/server/HttpChannelOverHttpCustom.java:[19,30]
```
```
sofa-registry/server/pom.xml 
```
```
 <jetty.version>[9.4.17.v20190418,)</jetty.version>
```
可能原因是Mavenc中央仓库中的jetty最新版本是 10.0.0-alpha0 用是是jdk11编译的 发布时间是:2019-07-13

### Environment

- SOFARegistry version: master and v5.2.0
- JVM version (e.g. `java -version`): 1.8.0_171
- OS version (e.g. `uname -a`): Win10 2018-11-10 14:38
- Maven version: 3.5.3
- IDE version: CMD

**Comment by jimchou800** [comment]
``` 
<jetty.version>[9.4.17.v20190418,)</jetty.version>
```
改成
```
<jetty.version>9.4.17.v20190418</jetty.version>
```
编译通过

**Comment by Synex-wh** [comment]
是的，这个区间引用是前几天jetty更新了10.0.0-alpha0 后，我们闭区间没有填写值引起的，这个我们后续fix了已经，建议你也改为<jetty.version>[9.4.17.v20190418,9.4.19.v20190610]</jetty.version>
