### ISSUE TITLE
TaskQueue.cleanCompletedTasks has redundant code

### ISSUE THREAD

**Issue by liyork** [sofastack/sofa-registry#46]
### Your question

TaskQueue.cleanCompletedTasks method return vod 
so the ```taskMap.size()``` is redundant

### Your scenes

in master brance

### Your advice

delete this one or other reason?

### Environment

- SOFARegistry version: master
- JVM version (e.g. `java -version`): jdk1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by Synex-wh** [comment]
This is really redundant code, we will fix it in the next version.
