### ISSUE TITLE
data的多副本是怎么保证一致性的呢？

### ISSUE THREAD

**Issue by huangyunbin** [sofastack/sofa-registry#6]

**Comment by wenweihu86** [comment]
@huangyunbin 看起来是没有保证一致性，数据是存在内存的。类似eureka。

**Comment by Synex-wh** [comment]
> @huangyunbin 看起来是没有保证一致性，数据是存在内存的。类似eureka。

data的多副本目前没有保持强一致性，对于一个服务id按照一致性hash算到一个data存储节点，这个节点就认为是这个服务id的主副本，session会定期进行数据比对保持这个dataid的数据和session一致，也就保证这个数据最终和client源一致。这个主副本节点data会进行其他两个副本复制，在备份副本变为主副本节点的时候（比如主副本结点宕机），这个新的头结点如果有和之前头结点不一致情况靠session再进行比对达到最终一致的
