### ISSUE TITLE
meta dataList version currentTimeMillis product must from source

### ISSUE THREAD

**Issue by Synex-wh** [sofastack/sofa-registry#73]
### Describe the bug

- The version number of the dataServer list information recorded by metaServer is generated by the timestamp. Each time a new node is added, the list is changed. The timestamp at the time of the new node is used as the version number. At present, multiple meta nodes are required to copy this version number , Now the code version number is generated inside the execution logic of the state machine, so that each execution may generate different version numbers on different nodes.

![image](https://user-images.githubusercontent.com/8018119/69715459-41a47780-1143-11ea-8bc7-3b9da61e5397.png)

- Modify the current version number to be passed in from the outside to ensure that it is generated only at the time of generation. The subsequent replication logic only copies the data and does not regenerate it.

**Comment by atellwu** [comment]
LGTM
