### ISSUE TITLE
 Register jaxrs service error 帮忙看看这个问题

### ISSUE THREAD

**Issue by dagou** [sofastack/sofa-registry#95]
ERROR main                             com.alipay.sofa.rpc.server.rest.RestServer - Register jaxrs service error
java.lang.RuntimeException: Class is not a root resource.  It, or one of its interfaces must be annotated with @Path: 
这个问题如何解决

**Comment by straybirdzls** [comment]
你好，请提供下更加详细的信息，包括复现步骤、环境等，另外这个问题看起来是 sofa-rpc 相关的？

**Comment by dagou** [comment]
sofa-rpc的&nbsp; 我之前用的是企业版 现在打算用开源版搭一个灾备环境&nbsp; 用的是 sofa-registry&nbsp; &nbsp;启动的时候 在rpc日志中 报这个错！




------------------&nbsp;Original&nbsp;------------------
