### ISSUE TITLE
the sofa-registry package have some problems

### ISSUE THREAD

**Issue by ivanljc2017** [sofastack/sofa-registry#99]
### Describe the bug
when i  executed "mvn clean package -DskipTests" in  window's dos,
the files distribution-session.xml,distribution-data.xml,distribution-meta.xml,distribution-integration.xml have  same problem.The "/" in linux is root directory , but in windows is not.
Like this:
        <file>
            <source>../../server/session/target/registry-server-session-executable.jar</source>
            <outputDirectory>/</outputDirectory>
            <destName>registry-session.jar</destName>
        </file>
        <file>
            <source>../../server/session/src/main/resources/logback-spring.xml</source>
            <outputDirectory>/conf</outputDirectory>
            <destName>logback-spring.xml</destName>
        </file>
        <file>
            <source>../version</source>
            <outputDirectory>/</outputDirectory>
            <destName>version_${project.version}</destName>
        </file>

### Environment

- SOFARegistry version: 5.4.2
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): windows 10
- Maven version:3.6.3
- IDE version:

**Comment by ivanljc2017** [comment]
No one answer me.The ecophere is so poor!

**Comment by khotyn** [comment]
我们找个环境试一下看看。

**Comment by khotyn** [comment]
It seems that this error does not prevent the package process and the package result in windows is correct.

Anyway, I create a PR #102 to fix this error.
